---
- name: Remove Duplicate Config
  file:
    state: absent
    path: /etc/php5/fpm/conf.d/newrelic.ini
  tags:
    - newrelic
    - housekeeping

- name: Configure sysmond | license_key
  lineinfile:
    state: present
    dest: /etc/newrelic/nrsysmond.cfg
    regexp: '^#* *license_key'
    line: 'license_key=***REMOVED***'
  tags:
    - configuration
    - precise-configuration
    - external-service
    - newrelic

- name: Configure sysmond | proxy
  lineinfile:
    state: present
    dest: /etc/newrelic/nrsysmond.cfg
    regexp: '^#* *proxy'
    line: "proxy={{ newrelic_proxy_address }}:{{ newrelic_proxy_port }}"
  when: newrelic_proxy_required
  tags:
    - configuration
    - precise-configuration
    - external-service
    - newrelic

- name: Configure PHP APM | newrelic.license
  lineinfile:
    state: present
    dest: /etc/php5/fpm/conf.d/20-newrelic.ini
    regexp: '^;* *newrelic\.license'
    line: 'newrelic.license = "***REMOVED***"'
  notify: Reload Service | php5-fpm
  when: newrelic_php_apm_enabled
  tags:
    - configuration
    - precise-configuration
    - external-service
    - newrelic
    - php

- name: Configure PHP APM | newrelic.appname
  lineinfile:
    state: present
    dest: /etc/php5/fpm/conf.d/20-newrelic.ini
    regexp: '^;* *newrelic\.appname'
    line: 'newrelic.appname = "{{ newrelic_appname }}"'
  notify: Reload Service | php5-fpm
  when: newrelic_php_apm_enabled
  tags:
    - configuration
    - precise-configuration
    - external-service
    - newrelic
    - php

- name: Configure PHP APM | newrelic.daemon.proxy
  lineinfile:
    state: present
    dest: /etc/php5/fpm/conf.d/20-newrelic.ini
    regexp: '^;* *newrelic\.daemon\.proxy'
    line: "newrelic.daemon.proxy = \"{{ newrelic_proxy_address }}:{{ newrelic_proxy_port }}\""
  notify: Reload Service | php5-fpm
  when: 'newrelic_php_apm_enabled and newrelic_proxy_required'
  tags:
    - configuration
    - precise-configuration
    - external-service
    - newrelic
    - php
