---
- name: Configure NewRelic License Key
  lineinfile:
    state: present
    dest: /etc/newrelic/nrsysmond.cfg
    regexp: '^#* *license_key'
    line: 'license_key=***REMOVED***'
  tags:
    - configuration
    - precise-configuration
    - external-service
    - newrelic

#  command: nrsysmond-config --set license_key=***REMOVED***

- name: Install NewRelic using NewRelic installer with license key
  shell: newrelic-install install executable=/bin/bash
  notify: Reload Service | php5-fpm
  when: newrelic_php_apm_enabled
  tags:
    - monitoring
    - using-newrelic
    - php
