---
- name: Install Packages | apt
  apt:
    state: latest
    pkg: "{{ item }}"
  with_items:
    - newrelic-sysmond
  tags:
    - software-installation
    - using-apt

- name: Preemptively Answer | PHP APM | newrelic.appname
  debconf:
    name: newrelic-php5
    question: newrelic-php5/application-name
    vtype: string
    value: "{{ newrelic_appname }}"
  when: newrelic_php_apm_enabled

- name: Preemptively Answer | PHP APM | newrelic.license
  debconf:
    name: newrelic-php5
    question: newrelic-php5/license-key
    vtype: string
    value: "{{ newrelic_license }}"
  when: newrelic_php_apm_enabled

- name: Install Packages | apt
  apt:
    state: latest
    pkg: "{{ item }}"
  with_items:
    - newrelic-php5
  when: newrelic_php_apm_enabled
  tags:
    - software-installation
    - using-apt

- name: Install PHP APM | newrelic-install
  shell: newrelic-install install
  args:
    executable: /bin/bash
  notify: service | php5-fpm | reloaded
  when: newrelic_php_apm_enabled
  tags:
    - monitoring
    - using-newrelic
    - php

- name: Install newrelic haproxy plugin gem
  gem: name=newrelic_haproxy_agent state=latest
  when: newrelic_haproxy_plugin_enabled

- name: Generate newrelic haproxy plugin configuration
  shell: newrelic_haproxy_agent install
  when: newrelic_haproxy_plugin_enabled

- name: Add newrelic haproxy plugin configuration
  template: src=newrelic_haproxy_agent.yml dest=/etc/newrelic/newrelic_haproxy_agent.yml
  when: newrelic_haproxy_plugin_enabled

- name: add init script for newrelic haproxy plugin
  copy: src=newrelic_haproxy_agent dest=/etc/init.d/newrelic_haproxy_agent mode=a+x
  when: newrelic_haproxy_plugin_enabled

- name: Run newrelic haproxy plugin process
  service: name=newrelic_haproxy_agent state=started enabled=yes
  when: newrelic_haproxy_plugin_enabled
