---
- name: Install Packages | apt
  apt:
    state: latest
    pkg: "{{ item }}"
  with_items:
    - newrelic-sysmond
  tags:
    - software-installation
    - using-apt

- name: Install Packages | apt
  apt:
    state: latest
    pkg: "{{ item }}"
  with_items:
    - newrelic-php5
  when: newrelic_php_apm_enabled
  tags:
    - software-installation
    - using-apt
